import { NextResponse } from 'next/server';
import { createClient } from '@/app/lib/supabase/server';
import { createClient as createSupabaseClient } from '@supabase/supabase-js';

// GET: fetch activities for a specific month or day + auto-generated stats
export async function GET(req: Request) {
    try {
        const { searchParams } = new URL(req.url);
        const dateStr = searchParams.get('date'); // YYYY-MM-DD
        const monthStr = searchParams.get('month'); // YYYY-MM
        const startDateParam = searchParams.get('startDate');
        const endDateParam = searchParams.get('endDate');

        const supabase = await createClient();
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

        const supabaseAdmin = createSupabaseClient(
            process.env.NEXT_PUBLIC_SUPABASE_URL!,
            process.env.SUPABASE_SERVICE_ROLE_KEY!
        );

        let query = supabaseAdmin.from('agent_activities').select('*').eq('agent_id', user.id);

        let propQuery = supabaseAdmin.from('properties').select('created_at').eq('owner_id', user.id);
        let leadQuery = supabaseAdmin.from('leads').select('created_at').eq('agent_id', user.id); // Assuming agent_id tracks lead ownership

        if (dateStr) {
            query = query.eq('date', dateStr);
            propQuery = propQuery.gte('created_at', `${dateStr}T00:00:00Z`).lt('created_at', `${dateStr}T23:59:59Z`);
            leadQuery = leadQuery.gte('created_at', `${dateStr}T00:00:00Z`).lt('created_at', `${dateStr}T23:59:59Z`);
        } else if (startDateParam && endDateParam) {
            query = query.gte('date', startDateParam).lte('date', endDateParam);
            propQuery = propQuery.gte('created_at', `${startDateParam}T00:00:00Z`).lte('created_at', `${endDateParam}T23:59:59Z`);
            leadQuery = leadQuery.gte('created_at', `${startDateParam}T00:00:00Z`).lte('created_at', `${endDateParam}T23:59:59Z`);
        } else if (monthStr) {
            const year = parseInt(monthStr.split('-')[0]);
            const month = parseInt(monthStr.split('-')[1]);
            const startDate = `${year}-${String(month).padStart(2, '0')}-01`;
            const nextMonth = month === 12 ? 1 : month + 1;
            const nextMonthYear = month === 12 ? year + 1 : year;
            const endDateExcl = `${nextMonthYear}-${String(nextMonth).padStart(2, '0')}-01`;

            query = query.gte('date', startDate).lt('date', endDateExcl);
            propQuery = propQuery.gte('created_at', `${startDate}T00:00:00Z`).lt('created_at', `${endDateExcl}T00:00:00Z`);
            leadQuery = leadQuery.gte('created_at', `${startDate}T00:00:00Z`).lt('created_at', `${endDateExcl}T00:00:00Z`);
        }

        const { data: manualActivities, error } = await query;
        if (error) throw error;

        const { data: props } = await propQuery;
        const { data: leads } = await leadQuery;

        // We can inject auto-generated rows so the frontend can easily merge or consume them
        const autoGenerated = [
            { activity_type: 'auto_new_listings', quantity: props?.length || 0, is_auto: true },
            { activity_type: 'auto_new_leads', quantity: leads?.length || 0, is_auto: true }
        ];

        return NextResponse.json({ activities: manualActivities || [], autoGenerated });
    } catch (e: any) {
        console.error('[Activities GET] Fatal Error:', e);
        return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
    }
}

// POST: Upsert an activity quantity for a given date manually
export async function POST(req: Request) {
    try {
        const { date, activity_type, quantity } = await req.json();

        if (!date || !activity_type || quantity === undefined) {
             return NextResponse.json({ error: 'Missing parameters' }, { status: 400 });
        }

        const supabase = await createClient();
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

        const supabaseAdmin = createSupabaseClient(
            process.env.NEXT_PUBLIC_SUPABASE_URL!,
            process.env.SUPABASE_SERVICE_ROLE_KEY!
        );

        const { data, error } = await supabaseAdmin.from('agent_activities').upsert({
            agent_id: user.id,
            date,
            activity_type,
            quantity: Number(quantity)
        }, {
            onConflict: 'agent_id, date, activity_type' // The unique constraint created in SQL
        }).select().single();

        if (error) {
             console.error('[Activities POST] Upsert error:', error);
             return NextResponse.json({ error: 'Failed to update activity' }, { status: 500 });
        }

        return NextResponse.json({ message: 'Saved successfully', activity: data });
    } catch (e: any) {
        return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
    }
}
