export const ROMANIAN_CITIES = [
    'Timișoara',
    'Dumbrăvița',
    'Giroc',
    'Ghiroda',
    'Moșnița Nouă',
    'Săcălaz',
    'Sânandrei',
    'Utvin',
    'Chisoda'
];

export const TIMISOARA_AREAS = [
    'Take Ionescu',
    'Circumvalațiunii',
    'Calea Aradului',
    'Calea Torontalului',
    'Calea Lipovei',
    'Complex Studențesc',
    'Buziașului',
    'Elisabetin',
    'Mehala',
    'Bucovina',
    'Freidorf',
    'Dâmbovița',
    'Telegrafului',
    'Calea Urseni',
    'Steaua',
    'Fabric',
    'Medicină',
    'Tipografilor',
    'Blașcovici',
    'UMT',
    'Fratelia',
    'Lunei',
    'Spitalul Județean',
    'Central',
    'Cetății',
    'Simion Bărnuțiu',
    'Traian',
    'Plopi',
    'Bălcescu',
    'Ronaț',
    'Badea Cârțan',
    'Lidia',
    'Brâncoveanu',
    'Favorit',
    'Calea Lugojului',
    'Bogdăneștilor',
    'Dorobanților',
    'Ciarda Roșie',
    'Ghirodei',
    'Braytim',
    'Soarelui',
    'Piața Maria',
    'Piața Unirii',
    'Sinaia',
    'Torontal',
    'Cetate',
    'Eso',
    'Planetei',
    'Vatra Satului'
].sort((a, b) => a.localeCompare(b, 'ro'));
