"use client";
import React, { useState, useEffect } from 'react';
import { Plus, Check, Phone, Calendar, FileText, Home, Users } from 'lucide-react';
import { format } from 'date-fns';
import PersonalConsistencyWidget from '@/app/components/dashboard/PersonalConsistencyWidget';

type ActivityConfig = {
    key: string;
    title: string;
    desc: string;
    goal: number;
    icon: any;
    color: string;
    iconBg: string;
};

const PROSPECTING_CONFIG: ActivityConfig[] = [
    { key: 'prospecting_call', title: 'Prospecting Calls', desc: 'Outbound sales calls', goal: 30, icon: Phone, color: 'bg-blue-600', iconBg: 'bg-blue-100 text-blue-600' },
    { key: 'prospecting_appt_scheduled', title: 'Appts Scheduled', desc: 'Booked showings/meetings', goal: 5, icon: Calendar, color: 'bg-indigo-600', iconBg: 'bg-indigo-100 text-indigo-600' },
    { key: 'prospecting_appt_realised', title: 'Appts Realised', desc: 'Actual meetings attended', goal: 3, icon: Check, color: 'bg-purple-600', iconBg: 'bg-purple-100 text-purple-600' },
    { key: 'prospecting_contract', title: 'Contracts Signed', desc: 'Listings or Sales closed', goal: 1, icon: FileText, color: 'bg-green-600', iconBg: 'bg-green-100 text-green-600' }
];

const LEADS_CONFIG: ActivityConfig[] = [
    { key: 'lead_call', title: 'Lead Follow-up Calls', desc: 'Inbound leads & follow-ups', goal: 20, icon: Phone, color: 'bg-orange-600', iconBg: 'bg-orange-100 text-orange-600' },
    { key: 'lead_appt_scheduled', title: 'Lead Appts Scheduled', desc: 'Booked lead showings', goal: 4, icon: Calendar, color: 'bg-red-600', iconBg: 'bg-red-100 text-red-600' },
    { key: 'lead_appt_realised', title: 'Lead Appts Realised', desc: 'Attended lead showings', goal: 2, icon: Check, color: 'bg-rose-600', iconBg: 'bg-rose-100 text-rose-600' },
];

export default function AgentActivities() {
    const [date, setDate] = useState(format(new Date(), 'yyyy-MM-dd'));
    const [activities, setActivities] = useState<Record<string, number>>({});
    const [autoStats, setAutoStats] = useState({ listings: 0, leads: 0 });
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);

    const fetchActivities = async () => {
        setLoading(true);
        try {
            const res = await fetch(`/api/activities?date=${date}`);
            const data = await res.json();
            
            if (data.activities) {
                const map: Record<string, number> = {};
                data.activities.forEach((a: any) => { map[a.activity_type] = a.quantity; });
                setActivities(map);
            }
            if (data.autoGenerated) {
                const ls = data.autoGenerated.find((a: any) => a.activity_type === 'auto_new_listings')?.quantity || 0;
                const ld = data.autoGenerated.find((a: any) => a.activity_type === 'auto_new_leads')?.quantity || 0;
                setAutoStats({ listings: ls, leads: ld });
            }
        } catch (e) {
            console.error(e);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchActivities();
    }, [date]);

    const increment = async (activity_type: string) => {
        if (saving) return;
        setSaving(true);
        
        // Optimistic UI Update
        const currentQty = activities[activity_type] || 0;
        setActivities({ ...activities, [activity_type]: currentQty + 1 });

        try {
            await fetch('/api/activities', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ date, activity_type, quantity: currentQty + 1 })
            });
        } catch (e) {
            console.error("Failed to save", e);
            // Revert optimistically
            setActivities({ ...activities, [activity_type]: currentQty });
        } finally {
            setSaving(false);
        }
    };

    const renderActivityBlock = (config: ActivityConfig) => {
        const qty = activities[config.key] || 0;
        const progress = Math.min((qty / config.goal) * 100, 100);

        return (
            <div key={config.key} className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm">
                <div className="flex items-center justify-between mb-4">
                    <div className="flex items-center gap-4">
                        <div className={`w-12 h-12 rounded-full flex items-center justify-center ${config.iconBg}`}>
                            <config.icon className="w-6 h-6" />
                        </div>
                        <div>
                            <h3 className="font-bold text-lg text-slate-800">{config.title}</h3>
                            <p className="text-sm text-slate-500">{config.desc}</p>
                        </div>
                    </div>
                    <div className="text-right">
                        <div className="text-2xl font-bold text-slate-800">{qty} <span className="text-sm text-slate-400 font-normal">/ {config.goal}</span></div>
                    </div>
                </div>

                <div className="w-full bg-slate-100 rounded-full h-2 mb-6 overflow-hidden">
                    <div className={`${config.color} h-2 rounded-full transition-all duration-500`} style={{ width: `${progress}%` }}></div>
                </div>

                <div className="flex justify-end gap-2">
                    <button 
                        onClick={() => increment(config.key)} 
                        disabled={saving}
                        className={`flex items-center gap-2 text-white px-4 py-2 rounded-lg font-medium shadow-sm transition-all focus:ring-2 focus:ring-offset-2 hover:opacity-90 active:scale-95 disabled:opacity-50 ${config.color}`}
                    >
                        <Plus className="w-4 h-4" /> Log +1
                    </button>
                </div>
            </div>
        );
    };

    return (
        <div className="max-w-4xl mx-auto space-y-8">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h1 className="text-3xl font-bold text-slate-900">Daily Tracker</h1>
                    <p className="text-slate-500 mt-1">Log your actions to hit your CRM pipeline targets.</p>
                </div>
                <div className="flex items-center gap-3">
                    <input 
                        type="date" 
                        value={date} 
                        onChange={(e) => setDate(e.target.value)}
                        className="border border-slate-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-orange-500 outline-none text-slate-700 shadow-sm"
                    />
                </div>
            </div>

            {loading ? (
                <div className="animate-pulse flex flex-col gap-6">
                    <div className="h-32 bg-slate-200 rounded-xl" />
                    <div className="h-32 bg-slate-200 rounded-xl" />
                </div>
            ) : (
                <>
                    {/* Auto-Generated Summary Widget */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
                        <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-xl p-6 text-white shadow-xl flex items-center gap-6">
                            <div className="w-14 h-14 bg-white/10 rounded-full flex items-center justify-center backdrop-blur-md">
                                <Home className="w-7 h-7 text-white" />
                            </div>
                            <div>
                                <h4 className="text-slate-300 font-medium tracking-wide text-sm uppercase">Auto-Generated</h4>
                                <div className="text-3xl font-bold mt-1">{autoStats.listings} <span className="text-lg font-normal text-slate-400">New Listings</span></div>
                            </div>
                        </div>

                        <div className="bg-gradient-to-br from-orange-600 to-amber-500 rounded-xl p-6 text-white shadow-xl flex items-center gap-6">
                            <div className="w-14 h-14 bg-white/20 rounded-full flex items-center justify-center backdrop-blur-md">
                                <Users className="w-7 h-7 text-white" />
                            </div>
                            <div>
                                <h4 className="text-orange-200 font-medium tracking-wide text-sm uppercase">Auto-Generated</h4>
                                <div className="text-3xl font-bold mt-1">{autoStats.leads} <span className="text-lg font-normal text-orange-200">New Leads</span></div>
                            </div>
                        </div>
                    </div>

                    <div className="space-y-6">
                        <h2 className="text-xl font-bold text-slate-800 border-b pb-2">Prospecting Activity</h2>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                            {PROSPECTING_CONFIG.map(renderActivityBlock)}
                        </div>

                        <h2 className="text-xl font-bold text-slate-800 border-b pb-2 mt-10">Lead Follow-up Activity</h2>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                            {LEADS_CONFIG.map(renderActivityBlock)}
                        </div>
                    </div>

                    <PersonalConsistencyWidget />
                </>
            )}
        </div>
    );
}
